name: CI
on: [push]
jobs:
  build:
    name: "ci"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.0
      - name: Install ddm
        run: |
          deno install --allow-all -n ddm -f https://raw.githubusercontent.com/ducthienbui97/ddm/master/bundle/ddm.js
          /home/runner/.deno/bin/ddm install
          ls
      - name: Test
        run: |
          /home/runner/.deno/bin/ddm test
      - name: Bundle
        run: |
          /home/runner/.deno/bin/ddm bundle src/index.ts bundle/ddm.js
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: development
          draft: false
          files: |
            bundle/ddm.js
