name: CI
on: 
  push:
    branches:
      - master  
    tags:
      - v*
jobs:
  build:
    name: "ci"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.0
      - name: Install ddm
        run: |
          deno install --allow-all -n ddm -f https://raw.githubusercontent.com/ducthienbui97/ddm/bundle/bundle/ddm.js
          /home/runner/.deno/bin/ddm install
          ls
      - name: Test
        run: |
          /home/runner/.deno/bin/ddm test
      - name: Bundle
        run: |
          mkdir bundle
          /home/runner/.deno/bin/ddm bundle src/index.ts bundle/ddm.js
      - name: Commit files
        if: startsWith(github.ref, 'refs/master/')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Rebuild bundle" -a
      - name: Push changes
        if: startsWith(github.ref, 'refs/master/')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'bundle'
          force: true
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bundle/ddm.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
